# **PROJET PYTHON : GESTION DU PERSONNEL**

Membres de l'équipe : Caroline, Natacha, Raïssa

**Objectif** : Développer un programme Python pour enregistrer les membres du personnel dans un fichier CSV et réaliser des calculs ou des traitements à partir de ce fichier

## PARTIE 1 : Demande de saisie des informations

### 1.1 Demande de la saisie de la civilité :
- Si la saisie est correcte, le programme passe au champ suivant.
- Si la saisie est incorrecte, un message apparait avec les consignes de saisie et la saisie de la civilité est redemandée.

In [ ]:
civilité=str(input("Saisir M. ou Mme : "))

if civilité=="M." or civilité=="Mme" :
    civilité=civilité

else :
    print("Attention! Saisir M. ou Mme")
    civilité=str(input("Saisir M. ou Mme : "))

Saisir M. ou Mme : Mme

### 1.2 Demande de la saisie du Nom :
- Chaque lettre du Nom saisi est comparée aux caractères autorisés dans la variable "alphabet".
- Quand la comparaison de l'ensemble des caractères du Nom n'est pas fausse, le programme passe au champ suivant.
- Dans la boucle for, si un des caractères ne fait pas parti de ceux autorisés dans la variable "alphabet", un message apparait avec les consignes de saisie et la saisie du Nom est redemandée. La boucle while recommense jusqu'à ce que le Nom soit conforme.
- break permet d'arrêter la boucle for au 1er caractère non conforme.Cela optimise la durée d'exécution.

In [ ]:
alphabet = ("abcdefghijklmnopqrstuvwxyz-'éèçAZERTYUIOPQSDFGHJKLMWXCVBN")
validation_nom = False
while not validation_nom:
    Nom = input('saisir le nom : ')
    validation_nom = True

    for lettre in Nom:
        if lettre not in alphabet:
            validation_nom = False
            print("ATTENTION! caractères spéciaux et chiffres non autorisés")
            break

saisir le nom : `$ùd$ù$ùed
ATTENTION! caractères spéciaux et chiffres non autorisés
saisir le nom : ù$êde`d
ATTENTION! caractères spéciaux et chiffres non autorisés
saisir le nom : ngwong

### 1.3 Demande de la saisie du Prénom :
Idem que pour le Nom

In [ ]:
alphabet = ("abcdefghijklmnopqrstuvwxyz-'éèçAZERTYUIOPQSDFGHJKLMWXCVBN")
validation_prenom = False
while not validation_prenom :
    Prénom = input('saisir le prénom : ')
    validation_prenom = True

    for lettre in Prénom:
        if lettre not in alphabet:
            validation_prenom = False
            print("ATTENTION! caractères spéciaux et chiffres non autorisés")
            break

saisir le prénom : Nadine

### 1.4 Demande de la saisie de l'âge :
- Tant que l'âge n'est pas compris dans l'interval, un message apparait avec les consignes de saisie et la saisie de l'âge est redemandée.
- Quand la saisie est correcte, le programme passe à l'étape suivante.

In [ ]:
validation = True
while validation :
    Age = int(input("Age : "))
    if 19 <= Age <= 65 :
        break
    else :
        print("ATTENTION ! Saisir un âge entre 19 et 65")

Age : 9
ATTENTION ! Saisir un âge entre 19 et 65
Age : 90
ATTENTION ! Saisir un âge entre 19 et 65
Age : 19

## PARTIE 2 : Enregistrement des informations saisies dans un fichier CSV

**Importation de la librairie Pandas**

In [ ]:
import pandas as pd

#### Création du fichier CSV
- Création du Data Frame df_perso
- Renommage des colonnes
- Sauvegarde du Data Frame df_perso dans un fichier CSV
- Lecture du fichier dans un nouveau Data Frame appelé df_personnel
- Affichage du Data Frame df_personnel
- A chaque exécution du programme une nouvelle ligne est créée avec les informations de la dernière personne saisie.

In [ ]:
df_perso=pd.DataFrame({
    "Date_Enregistrement":[date.today().strftime('%d/%m/%Y')],
    "Civilité":[civilité],
    "Nom":[Nom],
    "Prénom":[Prénom],
    "Age":[Age]
})
df_perso.columns = ["Date_Enregistrement","Civilité","Nom","Prénom","Age"]
df_perso.to_csv('personnel', index = False , mode = 'a', header=False)
df_personnel=pd.read_csv('personnel')
df_personnel

   Date_Enregistrement Civilité        Nom     Prénom  Age
0           01/02/2024      Mme     Durant      Marie   62
1           01/02/2024       M.     Dupond       Marc   39
2           01/02/2024       M.      Coute      Chris   53
3           01/02/2024      Mme      Coute      Nelly   50
4           01/02/2024      Mme      Coute      Nelly   50
5           01/02/2024       M.       Miro    Nicolas   25
6           01/02/2024       M.       Miro    Nicolas   25
7           01/02/2024      Mme      Bille       Vera   19
8           01/02/2024      Mme      Billi       Vera   19
9           01/02/2024      Mme      Billi       Vera   19
10          01/02/2024      Mme      Billi       Vero   19
11          01/02/2024      Mme      Billi       Vero   19
12          01/02/2024      Mme     Foudre     claire   32
13          01/02/2024      Mme      Ducro       Nina   25
14          01/02/2024       M.       Zero       Toto   42
15          01/02/2024       M.      Abbas    Gautier   49
16          01/02/2024      Mme     Jardin      Fleur   33
17          01/02/2024       M.       Van'  Jean-Loup   60
18          01/02/2024      Mme     Picard      Annie   56
19          01/02/2024       M.     Santos     Joseph   37
20          01/02/2024      Mme     Martin     Leanne   21
21          01/02/2024       M.      Radin       Mica   29
22          01/02/2024       M.     Ricard     Fabien   34
23          01/02/2024       M.   Langeais     Xavier   43
24          01/02/2024      Mme     Turpin      Agnes   46
25          01/02/2024       M.      colas     sophie   27
26          01/02/2024      Mme      Colas     Sophie   23
27          01/02/2024       M.      Bodin       René   64
28          01/02/2024       M.  Kerdalac'   Stéphane   45
29          01/02/2024       M.      Gabin       Jean   39
30          02/02/2024       M.    Ferrand    Charles   55
31          02/02/2024       M.     Dinard  Jean-Marc   55
32          02/02/2024       M.     Dinard  Jean-Marc   55
33          02/02/2024       M.     Daudin      Willy   55
34          02/02/2024       M.     Daudin      Willy   55
35          02/02/2024       M.     Daudin      Willy   55
36          02/02/2024       M.     Daudin      Willy   55
37          03/02/2024      Mme      Godin     Nadine   63
38          03/02/2024      Mme      Godin     Nadine   63
39          03/02/2024      Mme      Godin     Nadine   63
40          03/02/2024      Mme      Godin     Nadine   63
41          03/02/2024      Mme      Godin     Nadine   63
42          03/02/2024      Mme      Godin     Nadine   63
43          03/02/2024       M.     Armand     Thiery   51

## PARTIE 3 : Réalisation des calculs ou traitements

Pour la suite du projet, les calculs et traitements seront réalisés avec le fichier CSV transmis à l'ensemble des groupes : "donnees_prenoms_complementaires.csv"

#### Importation
- de la librairie Pandas
- de la librairie Numpy

In [ ]:
import numpy as np
import pandas as pd

**Affichage** du répertoire de travail où se trouve le fichier "donnees_prenoms_complementaires.csv"

In [ ]:
import os
chemin = os.getcwd()
print(chemin)

C:\Users\cefim\DATA WOMEN\PYTHON

**Lecture** du fichier CSV en indiquant son emplacement

In [ ]:
df_RH = pd.read_csv("C:/Users/cefim/DATA WOMEN/PYTHON/donnees_prenoms_complementaires.csv", delimiter=';',encoding='ANSI')
df_RH

   Civilite                 Nom      Prenom  Age        Date
0       Mme              Loddon      Sélène   42  01/01/2024
1       Mme            Skakunas   Styrbjörn   36  01/01/2024
2       Mme          O'Siaghail        Eléa   59  01/01/2024
3       Mme             Boswell      Léonie   40  01/01/2024
4       Mme             Boswell      Léonie   40  01/01/2024
5         M              Yedall         Léo   39  01/01/2024
6       Mme               Krook   Bénédicte   38  01/01/2024
7       Mme             Painter  Simplifiés   52  02/01/2024
8         M         Rope-Hackly       Börje   57  02/01/2024
9       Mme      Tresvina-Irwin         Ráo   49  02/01/2024
10        M         Kitchingman      Alexis   51  02/01/2024
11        M  Gruszka-Massenhove         Pål   57  02/01/2024
12        M          Le Provost      Franck   50  02/01/2024
13      Mme       Alexandersson   Véronique   29  02/01/2024
14      Mme           Vanichkin   Bénédicte   19  03/01/2024
15        M             Bambury      Pierre   49  03/01/2024
16        M             Bambury      Pierre   49  03/01/2024
17        M             Sellars       Roger   36  03/01/2024
18      Mme             Tomblin     Pélagie   65  04/01/2024
19      Mme       Dowsey-Worton      Maëlla   43  04/01/2024
20      Mme       Coots-Housego   Véronique   60  04/01/2024
21        M              Leggon         Ali   41  04/01/2024
22      Mme            McSherry   Andréanne   27  04/01/2024
23      Mme              Yendle     Camélia   43  04/01/2024
24        M        Quartermaine        Maël   43  05/01/2024
25      Mme      Ghiotto-Zecchi     Mélodie   45  05/01/2024
26      Mme               Peele          Dù   47  05/01/2024
27      Mme              Overel      Céline   45  05/01/2024
28      Mme             Craigie       Laïla   28  05/01/2024
29      Mme              McLeod          Mà   32  05/01/2024
30      Mme               Arson        Inès   39  05/01/2024
31      Mme            Pieracci      Eloïse   42  05/01/2024

**Afficher** les informations du Data Frame df_RH pour connaître :
- le nombre total de lignes
- le nombre de colonnes
- le type des données de chaque colonne
- le nombre de chaque type de données
- la mémoire utilisée par le Data frame

In [ ]:
df_RH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Civilite  32 non-null     object
 1   Nom       32 non-null     object
 2   Prenom    32 non-null     object
 3   Age       32 non-null     int64
 4   Date      32 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.4+ KB

**Afficher** les informations statistiques de notre Data Frame :
- nombre de lignes remplies,
- la moyenne,
- l'écart-type,
- la valeur minimale,
- le 1er quartile,
- la médiane,
- le 3èm" quartile
- la valeur maximale

In [ ]:
df_RH.describe()

             Age
count  32.000000
mean   43.500000
std    10.305025
min    19.000000
25%    38.750000
50%    43.000000
75%    49.250000
max    65.000000

### 3.1 Nombre de personnes saisies

Utilisation de la fonction **len()** pour compter le nombre de lignes

In [ ]:
NbPerso = len(df_RH)
print("Nombre de personnes saisies : ",NbPerso)

Nombre de personnes saisies :  32

### 3.2 Pourcentage d'hommes

Comptage du nombre d'hommes de la colonne "Civilité" de notre Data Frame df_RH avec la fonction **value.counts()**, puis calcul du pourcentage d'hommes.

In [ ]:
NbHommes = df_RH['Civilite'].value_counts()['M']
Pourcent_H = (NbHommes/NbPerso)*100
print("Pourcentage d'hommes : ",Pourcent_H, '%')

Pourcentage d'hommes :  31.25 %

### 3.3 Age moyen/médian/étendue des âges

#### a.Age moyen de l'ensemble des personnes

Calcul de la moyenne des valeurs de la colonne "Age" de notre Data Frame df_RH en utilisant la fonction **mean()**

In [ ]:
Moyenne = df_RH['Age'].mean()
print('Age moyen des personnes : ',Moyenne,'ans')

Age moyen des personnes :  43.5 ans

**b.Age médian de l'ensemble des personnes**

Calcul de la médiane des valeurs de la colonne "Age" de notre Data Frame df_RH en utilisant la fonction **median()**

In [ ]:
Medianne = df_RH['Age'].median()
print('Age médian des personnes : ',Medianne,'ans')

Age médian des personnes :  43.0 ans

**c.Etendue des âges des personnes**

Calcul de l'étendue des valeurs de la colonne "Age" de notre Data Frame df_RH en utilisant la différence entre les fonctions **max()** et **min()**.

In [ ]:
AgeMax = df_RH['Age'].max()
AgeMin = df_RH['Age'].min()
EtendueAge = AgeMax - AgeMin
print('Etendue des âges : ',EtendueAge, 'ans')

Etendue des âges :  46 ans

### 3.4 Afficher le Nom et le Prénom du(des) personne(s) la(les) plus jeune(s)

La fonction **dataframe.loc()** permet de récupérer pour toutes les lignes où l'âge est le plus petit, les données des colonnes "Nom" et "Prenom"

In [ ]:
PlusJeune = df_RH.loc[df_RH['Age']==df_RH['Age'].min(), ['Nom','Prenom']]
print(PlusJeune)

          Nom     Prenom
14  Vanichkin  Bénédicte

### 3.5 Afficher le Nom et le Prénom du(des) personne(s) la(less) plus agée(s)

La fonction **dataframe.loc()** permet de récupérer pour toutes les lignes où l'âge est le plus grand, les données des colonnes "Nom" et "Prenom"

In [ ]:
PlusVieux = df_RH.loc[df_RH['Age']==df_RH['Age'].max(), ['Nom','Prenom']]
print(PlusVieux)

        Nom   Prenom
18  Tomblin  Pélagie

### 3.6 Pourcentage de noms composés

- La variable "compteur" compte le nombre de caractères "-" de chaque ligne pour la colonne "Nom".
- La fonction **sum()** fait la somme des "-" de la colonne "Nom" et donne donc le nombre total de noms composés
- Enfin on calcule le pourcentage de noms composés par rapport au nombre total de personnes saisies

In [ ]:
compteur =  df_RH['Nom'].str.count('-')
#print(compteur)
NbNomCompo = sum(compteur)
print("Nombre de Noms composés : ",NbNomCompo)
Pourcent_NomComp = (NbNomCompo/NbPerso)*100
print("Pourcentage de noms composés : ",Pourcent_NomComp, '%')

Nombre de Noms composés :  6
Pourcentage de noms composés :  18.75 %

### 3.7 Classement des données par ordre alphabétique du nom de famille

Pour trier des données par ordre alphabétique en utilisant une colonne spécifique de notre data frame, nous utilisons la fonction **dataframe.sort_values(by=['nom de la colonne que l'on veut trier'])**. Cette fonction trie de A à Z par défaut.

In [ ]:
OrdreAlpha = df_RH.sort_values(by=['Nom'])
print(OrdreAlpha)

   Civilite                 Nom      Prenom  Age        Date
13      Mme       Alexandersson   Véronique   29  02/01/2024
30      Mme               Arson        Inès   39  05/01/2024
15        M             Bambury      Pierre   49  03/01/2024
16        M             Bambury      Pierre   49  03/01/2024
3       Mme             Boswell      Léonie   40  01/01/2024
4       Mme             Boswell      Léonie   40  01/01/2024
20      Mme       Coots-Housego   Véronique   60  04/01/2024
28      Mme             Craigie       Laïla   28  05/01/2024
19      Mme       Dowsey-Worton      Maëlla   43  04/01/2024
25      Mme      Ghiotto-Zecchi     Mélodie   45  05/01/2024
11        M  Gruszka-Massenhove         Pål   57  02/01/2024
10        M         Kitchingman      Alexis   51  02/01/2024
6       Mme               Krook   Bénédicte   38  01/01/2024
12        M          Le Provost      Franck   50  02/01/2024
21        M              Leggon         Ali   41  04/01/2024
0       Mme              Loddon      Sélène   42  01/01/2024
29      Mme              McLeod          Mà   32  05/01/2024
22      Mme            McSherry   Andréanne   27  04/01/2024
2       Mme          O'Siaghail        Eléa   59  01/01/2024
27      Mme              Overel      Céline   45  05/01/2024
7       Mme             Painter  Simplifiés   52  02/01/2024
26      Mme               Peele          Dù   47  05/01/2024
31      Mme            Pieracci      Eloïse   42  05/01/2024
24        M        Quartermaine        Maël   43  05/01/2024
8         M         Rope-Hackly       Börje   57  02/01/2024
17        M             Sellars       Roger   36  03/01/2024
1       Mme            Skakunas   Styrbjörn   36  01/01/2024
18      Mme             Tomblin     Pélagie   65  04/01/2024
9       Mme      Tresvina-Irwin         Ráo   49  02/01/2024
14      Mme           Vanichkin   Bénédicte   19  03/01/2024
5         M              Yedall         Léo   39  01/01/2024
23      Mme              Yendle     Camélia   43  04/01/2024

### 3.8 Classement des données par ordre décroissant des âges

On utilise la même fonction qu'au 3.7 mais cette fois, pour trier dans l'ordre décroissant, il faut préciser que l'ordre croissant par défaut est "Faux".

In [ ]:
DecAge = df_RH.sort_values(by=['Age'], ascending=False)
print(DecAge)

   Civilite                 Nom      Prenom  Age        Date
18      Mme             Tomblin     Pélagie   65  04/01/2024
20      Mme       Coots-Housego   Véronique   60  04/01/2024
2       Mme          O'Siaghail        Eléa   59  01/01/2024
8         M         Rope-Hackly       Börje   57  02/01/2024
11        M  Gruszka-Massenhove         Pål   57  02/01/2024
7       Mme             Painter  Simplifiés   52  02/01/2024
10        M         Kitchingman      Alexis   51  02/01/2024
12        M          Le Provost      Franck   50  02/01/2024
15        M             Bambury      Pierre   49  03/01/2024
16        M             Bambury      Pierre   49  03/01/2024
9       Mme      Tresvina-Irwin         Ráo   49  02/01/2024
26      Mme               Peele          Dù   47  05/01/2024
25      Mme      Ghiotto-Zecchi     Mélodie   45  05/01/2024
27      Mme              Overel      Céline   45  05/01/2024
24        M        Quartermaine        Maël   43  05/01/2024
23      Mme              Yendle     Camélia   43  04/01/2024
19      Mme       Dowsey-Worton      Maëlla   43  04/01/2024
0       Mme              Loddon      Sélène   42  01/01/2024
31      Mme            Pieracci      Eloïse   42  05/01/2024
21        M              Leggon         Ali   41  04/01/2024
4       Mme             Boswell      Léonie   40  01/01/2024
3       Mme             Boswell      Léonie   40  01/01/2024
5         M              Yedall         Léo   39  01/01/2024
30      Mme               Arson        Inès   39  05/01/2024
6       Mme               Krook   Bénédicte   38  01/01/2024
17        M             Sellars       Roger   36  03/01/2024
1       Mme            Skakunas   Styrbjörn   36  01/01/2024
29      Mme              McLeod          Mà   32  05/01/2024
13      Mme       Alexandersson   Véronique   29  02/01/2024
28      Mme             Craigie       Laïla   28  05/01/2024
22      Mme            McSherry   Andréanne   27  04/01/2024
14      Mme           Vanichkin   Bénédicte   19  03/01/2024

### 3.9 Nom de famille contenant le plus de voyelles

In [ ]:
ListeVoyelle = "AaEeIiOoUuYy"
compt_voyelle = df_RH['Nom'].str.count("AaEeIiOoUuYy")
print(compt_voyelle)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
Name: Nom, dtype: int64

### 3.10 Nom de famille le plus long

### 3.11 Identification des doublons

- Pour identifier les doublons nous utilisons la fonction **dataframe.duplicate()**. Dans ce cas,par défaut, toutes les lignes dupliquées sont affichées sauf la première de chaque série de doublons.
- Pour afficher toutes les lignes en doublon, il faut ajouter (keep=False)
- Par défaut, toutes les colonnes sont utilisées pour identifier si une ligne est un doublon ou non.

In [ ]:
DoublonsLigne = df_RH[df_RH.duplicated(keep=False)]
print("Liste des lignes en doublon : ")
print(DoublonsLigne)

Liste des lignes en doublon :
   Civilite      Nom  Prenom  Age        Date
3       Mme  Boswell  Léonie   40  01/01/2024
4       Mme  Boswell  Léonie   40  01/01/2024
15        M  Bambury  Pierre   49  03/01/2024
16        M  Bambury  Pierre   49  03/01/2024